### ISSUE TITLE
stdout/logs for Prometheus 

### ISSUE THREAD

**Issue by dineshspathak** [zerodha/mii-lama#7]
Hi while inspecting the stdout/logs for Prometheus with **docker-compose logs -f prometheus**, its getting stuck on starting rule manager, is this ok?

prometheus    | ts=2023-06-19T07:17:47.620Z caller=manager.go:974 level=info component="rule manager" msg="Starting rule manager..."

<img width="963" alt="image" src="https://github.com/zerodha/mii-lama/assets/136902652/4cba8915-b290-4caa-adbe-d65ae2039be4">

**Comment by dineshspathak** [comment]
docker-compose logs -f results

<img width="610" alt="image" src="https://github.com/zerodha/mii-lama/assets/136902652/9f6773e6-bbed-4309-b7c5-dd09392b3614">

**Comment by mr-karan** [comment]
Yeah prometheus logs are INFO Level, so that is okay.

For the config error, please ensure you've followed this step as mentioned in README: https://github.com/zerodha/mii-lama#2-download-config-files

```
Download [config.sample.toml](https://github.com/zerodha/mii-lama/blob/main/config.sample.toml) and save it alongside docker-compose.yml as config.toml on the master system.
```

`config.toml` should exist in the directory where `docker-compose.yml` is present. There was a small issue where the `docker-compose.yml` expected a sample file, hence the error you're seeing. It's fixed in https://github.com/zerodha/mii-lama/commit/220617ebec1cf4a04a75a0b7f85c862a5b503f8f. Please re-download the `docker-compose.yml` and try again.

Thanks

**Comment by mr-karan** [comment]
Closing in favour of https://github.com/zerodha/mii-lama/issues/8
